name: Build and Test

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix: # Find available options here: https://docs.github.com/en/actions/using-jobs/choosing-the-runner-for-a-job
        os: 
        - ubuntu-latest
        # - windows-latest
        - macos-latest
        build_type:
        - Release
        - Debug
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: |
        ctest -C ${{ matrix.build_type }}
